# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Economía
tagline:          'Economía, Pensamiento y otros'
description:      'Una prueba atómica'
url:              https://fmgarciadiaz.github.io
baseurl:          # the optional subpath of your site, e.g. "/blog"

author:
  name:           'Fer GD'
  url:            https://twitter.com/fergd1978

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.4.1
sidebar_home_link:  true
github:
  repo:             https://github.com/fongandrew/hydeout

disqus:
  shortname: fmgarciadiaz-github-io

google_analytics: UA-105397114-1
